mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.garen.cas.mybatis.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.27.22.41:3306/cas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: cas
      password: hPRJZbHOv2MkSP3Sox00
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      database: 0
      host: 120.27.22.41
      port: 6379
      password:
      timeout: 6000
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
server:
  port: 9090
  tomcat:
    max-threads: 1024
    uri-encoding: utf-8