package org.garen.cas.mybatis.mapper;

import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.garen.cas.mybatis.domain.App;
import org.garen.cas.mybatis.domain.AppQuery;

public interface AppMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    long countByExample(AppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int deleteByExample(AppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int insertSelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    List<App> selectByExample(AppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    App selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") App record, @Param("example") AppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int updateByExample(@Param("record") App record, @Param("example") AppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated Thu Oct 19 21:41:54 CST 2017
     */
    int updateByPrimaryKey(App record);
}