package org.garen.cas.mybatis.mapper;

import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.garen.cas.mybatis.domain.UserBase;
import org.garen.cas.mybatis.domain.UserBaseQuery;

public interface UserBaseMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    long countByExample(UserBaseQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int deleteByExample(UserBaseQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int insertSelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    List<UserBase> selectByExample(UserBaseQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    UserBase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserBase record, @Param("example") UserBaseQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByExample(@Param("record") UserBase record, @Param("example") UserBaseQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByPrimaryKeySelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByPrimaryKey(UserBase record);
}