package org.garen.cas.mybatis.mapper;

import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.garen.cas.mybatis.domain.UserApp;
import org.garen.cas.mybatis.domain.UserAppQuery;

public interface UserAppMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    long countByExample(UserAppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int deleteByExample(UserAppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int insert(UserApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int insertSelective(UserApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    List<UserApp> selectByExample(UserAppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    UserApp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserApp record, @Param("example") UserAppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByExample(@Param("record") UserApp record, @Param("example") UserAppQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByPrimaryKeySelective(UserApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_app
     *
     * @mbg.generated Tue Oct 24 00:34:15 CST 2017
     */
    int updateByPrimaryKey(UserApp record);
}